engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - php
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- core/Group/Plugin/**/*
- test/**/*
- config/**/*